import streamlit as st
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv ()

st.title("Denise's Chatbox")

client = OpenAI()

# Part 2 - Enter Name
st.header("Part 2 - Enter Name")
# 1. Ask the user to enter their name.
st.session_state.name = st.text_input("What's your name?")

# Part 3 - Display Welcome Message
st.header("Part 3 - Display Welcome Message")
# 2. If the user enters their name and clicks a button, display a welcome message.
st.session_state.button_value = st.button("Click Me")

if st.session_state.name != "" and st.session_state.button_value == True:
    st.write(f"Hello, {st.session_state.name}")

# Part 4 - Display Name (AI Generated)
st.header("Part 4 - Display Name (AI Generated)")
# 3. The welcome message should be generated by GPT-4o.
if st.session_state.name != "" and st.session_state.button_value == True:
    response = client.responses.create(
        model="gpt-4o",
        input=f"Greet {st.session_state.name} and make them welcome.",
    )
    st.write(response.output_text)

# Part 5 - Display Welcome based on a Persona
st.header("Part 5 - Display Welcome based on a Persona")
# 4. The user can select different personas to be welcomed by.
st.session_state.option = st.selectbox(
    "What persona?",
    ("Shark", "Cow", "Clown", "Donald Trump"),
)

if st.session_state.name != "" and st.session_state.button_value == True and st.session_state.option != "":
    response = client.responses.create(
        model="gpt-4o",
        instructions=f"You must respond as if you are a: {st.session_state.option}",
        input=f"Greet {st.session_state.name} and make them welcome."
    )
    st.write(response.output_text)

    abcd